# Generated by Django 4.2 on 2023-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Yeardata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(blank=True, null=True)),
                (
                    "number_14_49_avg_digital_inclusion_index",
                    models.FloatField(
                        blank=True,
                        db_column="14-49_Avg_Digital_Inclusion_Index",
                        null=True,
                    ),
                ),
                (
                    "number_50_avg_digital_inclusion_index",
                    models.FloatField(
                        blank=True,
                        db_column="50+_Avg_Digital_Inclusion_Index",
                        null=True,
                    ),
                ),
                (
                    "number_14_49_avg_digital_accessibility_index",
                    models.FloatField(
                        blank=True,
                        db_column="14-49_Avg_Digital_Accessibility_Index",
                        null=True,
                    ),
                ),
                (
                    "number_50_avg_digital_accessibility_index",
                    models.FloatField(
                        blank=True,
                        db_column="50+_Avg_Digital_Accessibility_Index",
                        null=True,
                    ),
                ),
                (
                    "number_14_49_avg_digital_ability_index",
                    models.FloatField(
                        blank=True,
                        db_column="14-49_Avg_Digital_Ability_Index",
                        null=True,
                    ),
                ),
                (
                    "number_50_avg_digital_ability_index",
                    models.FloatField(
                        blank=True, db_column="50+_Avg_Digital_Ability_Index", null=True
                    ),
                ),
            ],
            options={"db_table": "yearData", "managed": False,},
        ),
    ]
