# Generated by Django 4.2 on 2023-04-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fit5120backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100, unique=True)),
                ("count", models.IntegerField(default=1)),
            ],
        ),
    ]
